### ISSUE TITLE
我之前也做过一个这样的库 哈哈～

### ISSUE THREAD

**Issue by farmerjohngit** [yrom/shrinker#2]
因为我公司工程拆成了多个aar，导致R.class很多。所以也写了个这样的库。看了下大家思路差不多，不过我没用transform
https://github.com/meili/ThinRPlugin

**Comment by yrom** [comment]
殊途同归嘛。用Transform API有个好处是，能够更早的处理R.class

**Comment by yuger** [comment]
确实可以去除R.class，减小几十KB，但是添加postprocessing{removeUnusedCode=true}之后与minifiEnabled和混淆规则等冲突，日志： 
The `setShrinkResources` method cannot be used with together with the `postProcessing` block.
The `proguardFile` method cannot be used with together with the `postProcessing` block.
The `setMinifyEnabled` method cannot be used with together with the `postProcessing` block.
两者是不共存的，该怎么处理？现在我只能暂且去除`postprocessing{removeUnusedCode=true}`这段了。

@farmerjohngit 你的那个库我以前也用过，好像是导入失败还是没起作用或者不记得什么原因，最后没有用。

**Comment by farmerjohngit** [comment]
嗯，我那个对应的android plugin版本比较老了，后面转做后端就没维护了

**Comment by yuger** [comment]
@farmerjohngit 这个库怎么兼容`postprocessing{removeUnusedCode=true}` 与 `minifiEnabled` 呢？

**Comment by MIkeeJY** [comment]
@farmerjohngit 这个库怎么兼容postprocessing{removeUnusedCode=true} 与 minifiEnabled 呢？

**Comment by farmerjohngit** [comment]
@yuger @MIkeeJY  已经不做android很久了
